### ISSUE TITLE
Feature: Support for bitwise operations

### ISSUE THREAD

**Issue by brocococonut** [ganigeorgiev/fexpr#2]
It'd be great if we could do things like Bitwise operations with this. The standard across most *sql* flavours (and programming languages) uses operators like `&` for ANDing things together, `|` For bitwise OR, as well as `<<` and `>>` for bit shifting left and right respectively.

These kinds of operations are especially useful when it comes to bitmasking for things like permissions.

**Comment by ganigeorgiev** [comment]
No sorry, I'm not planning working on this.
